# server:
#   port: 8080

# spring:
#   application:
#     name: USERS

# # eureka client 설정 추가
# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://192.168.0.157:8088/eureka

#   instance:
#     instance-id: USERS:8080  # 고정 값으로 설정
#     lease-renewal-interval-in-seconds: 10
#     lease-expiration-duration-in-seconds: 30

#   resources:
#     static-locations: classpath:/static/


eureka:
  client:
    service-url:
      defaultZone: http://shortpingoo-app-eureka-server.shortpingoo.svc.cluster.local:8088/eureka/  # Kubernetes 클러스터 내 Eureka Server URL
    register-with-eureka: true  # Eureka Server에 등록하도록 설정
    fetch-registry: true        # Eureka Server의 레지스트리를 가져오도록 설정

  instance:
    instance-id: backend-service:8080  # Eureka에 등록될 인스턴스 ID
    prefer-ip-address: true            # IP 주소로 등록하도록 설정
