server:
  port: 8080

spring:
  application:
    name: users

# eureka client 설정 추가
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8088/eureka